name: femn
description: "A new Flutter project."
publish_to: 'none'
version: 5.0.5+5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_storage: ^13.0.0
  image_picker: ^1.2.1
  camera: ^0.11.2+1
  video_player: ^2.10.1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  provider: ^6.1.5+1
  flutter_staggered_grid_view: ^0.7.0
  timeago: ^3.7.1
  share_plus: ^12.0.1
  uuid: ^4.5.1
  permission_handler: ^12.0.1
  chewie: ^1.12.1
  google_fonts: ^6.3.0
  iconsax: ^0.0.8
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  flutter_markdown: ^0.7.7+1
  equatable: ^2.0.7
  archive: ^4.0.7
  image_cropper: ^9.1.0
  record: ^6.1.1
  audioplayers: ^6.5.0
  vibration: ^3.1.3
  wave: ^0.2.2
  flutter_sound: ^9.28.0
  file_picker: ^10.3.8
  collection: ^1.19.1
  fuzzywuzzy: ^1.2.0
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^2.2.2
  rxdart: ^0.28.0
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  pdf: ^3.11.3
  percent_indicator: ^4.2.5
  table_calendar: ^3.2.0
  fl_chart: ^0.68.0
  flutter_feather_icons: ^2.0.0+1
  photo_manager: ^3.8.3
  video_thumbnail: ^0.5.6
  firebase_vertexai: ^2.2.0
  flutter_animate: ^4.5.2
  google_generative_ai: ^0.4.7
  app_links: ^6.4.1
  encrypt: ^5.0.3
  open_filex: ^4.7.0
  printing: ^5.14.2
  local_auth: ^2.3.0
  firebase_app_check: ^0.4.1+4
  image: ^4.5.4
  http: ^1.6.0
  path: ^1.9.1
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher_foreground.png" # Fallback for older devices
  min_sdk_android: 21 
  adaptive_icon_background: "#AD80BF" # Your purple color
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"
  adaptive_icon_foreground_inset: 25 # Shrinks logo to prevent cutting off

flutter_native_splash:
  color: "#AD80BF"                # Updated to your Purple hex
  image: assets/ic_launcher_foreground.png  # Updated to match your App Icon
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/femnlogotxt.png
    - assets/femnlogo.png
  fonts:
  - family: Helvetica
    fonts:
      - asset: assets/Helvetica.ttf
        weight: 400
      - asset: assets/Helvetica-Bold.ttf
        weight: 700
